# Generated by Django 5.2.14 on 2026-05-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gewicht', models.FloatField()),
                ('lengte_cm', models.FloatField()),
                ('leeftijd', models.IntegerField()),
                ('geslacht', models.CharField(max_length=10)),
                ('bmi', models.FloatField()),
                ('bmr', models.FloatField()),
            ],
        ),
    ]
